### ISSUE TITLE
是否有排序功能?

### ISSUE THREAD

**Issue by zimaoxy** [zthxxx/hexo-theme-Wikitten#9]
初次接触Hexo，打算使用您的主题制作一个帮助文档，请问在左边挂件显示的文章和分类是否可以自定义排序？

**Comment by zthxxx** [comment]
Oh, it default sorted by article title and category name, so you can let your article and category like this:

```
_posts/1-xxxx/1.1-xxxx.md
_posts/1-xxxx/1.2-xxxx.md
_posts/2-xxxx/2.1-xxxx.md
_posts/2-xxxx/2.2-xxxx.md
```
and so on, it will be sorted.

**Comment by zimaoxy** [comment]
谢谢，期待推出文章与目录的排序功能~目前我找到了文章的排序插件，分类目录暂时未找到~

**Comment by rosuH** [comment]
@zimaoxy 请问能告知一下插件名吗？

@zthxxx  顺便问一下，我已经按照序号给文章命名了，然而...总是会在出现一些错误，比如下图：

![](https://ooo.0o0.ooo/2017/04/23/58fc5a4e7e802.jpg)

**Comment by rosuH** [comment]
@zimaoxy 方便告知一下文章排序插件吗？我也在找但没找到~谢谢

**Comment by rosuH** [comment]
@zimaoxy 谢谢。之所以删了回复是因为后面决定直接更改文件名来排序了~不过您的回复依旧很有帮助.

**Comment by maksyuki** [comment]
I have sorted my article title name but it seem no to work. The article order in categories sidebar  still be wrong, this are snapshoots of wrong in article _**Problem**_：[Problem](https://microdynamics.github.io/)

**Comment by zthxxx** [comment]
@maksyuki 
because it's order by **Folder name** or **File name**, rather than *Title name* in the MD front matter.

see this:

![btzfvb4vo qfxv_of ora60](https://user-images.githubusercontent.com/15135943/37768520-ec61fe10-2e08-11e8-9927-44f0b811580f.png)

![o h7z67l9 kx3lebkh6 1](https://user-images.githubusercontent.com/15135943/37768527-f11608e8-2e08-11e8-9d9c-70f4a41d612d.png)

**Comment by zthxxx** [comment]
also recommend to using name format like `1-2-xxxx.md`, if u want a order list.

using symbol `-` instead of `.` in file name

**Comment by maksyuki** [comment]
Thanks~
